name: Build binaries

on:
  push:
    branches: [ master, build, dev]
  pull_request:
    branches: [ master, build, dev]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 16
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install windows dependencies
      if: matrix.os == 'windows-latest'
      run: |
        pip install pywin32
    - name: Install macos dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install create-dmg
    - name: Build executable (windows)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        ./build-windows.ps1
    - name: Build executable (macos)
      if: matrix.os == 'macos-latest'
      run: |
        make build_osx
    - name: Build executable (ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        make build_linux
    - uses: actions/upload-artifact@v2
      if: matrix.os == 'windows-latest'
      with:
        name: BlobBackup_windows_v1.0.1.zip
        path: BlobBackup
    - uses: actions/upload-artifact@v2
      if: matrix.os == 'macos-latest'
      with:
        name: BlobBackup_osx_v1.0.1.dmg
        path: BlobBackup.dmg
    - uses: actions/upload-artifact@v2
      if: matrix.os == 'ubuntu-latest'
      with:
        name: BlobBackup_linux_v1.0.1.zip
        path: BlobBackup
